#!/usr/bin/env python3
"""
gen_video.py — Generate YouTube-ready podcast video for The Daily Dagoth.

Usage:
    python3 gen_video.py <episode_dir> [output_mp4]

Example:
    python3 gen_video.py /root/.openclaw/workspace/skills/podcast-gen/output/EP008-is-xbox-cooked

Requires:
    <episode_dir>/captions.ass   (generated by gen_captions.py)
    <episode_dir>/podcast.mp3
    /root/.openclaw/workspace/skills/podcast-gen/assets/cover.png

Output: <episode_dir>/<basename>.mp4  (or override with second arg)

Video layout (1920x1080):
  ┌──────────────────────────────────────────────────────┐
  │  Background: cover art, blurred + dimmed             │
  │                                                      │
  │         ┌────────────────────────┐                   │
  │         │  Circular CQT waveform │                   │
  │         │  (showcqt, 800x800,    │                   │
  │         │   screen-blended,      │                   │
  │         │   slow hue cycling)    │                   │
  │         └────────────────────────┘                   │
  │                                                      │
  │   [DAGOTH: caption text here in gold]                │
  └──────────────────────────────────────────────────────┘

Filter notes (what was tested / what works):
  - showcqt:    Produces colorful frequency spectrum. count=1 gives single channel.
                csp=bt709 for proper color. Size must be square for circular crop.
                Screen blend with background makes black bg transparent.
  - geq:        Used for circular crop on YUV. lum/cb/cr channels.
                hypot(X-W/2,Y-H/2) < R to mask out-of-circle pixels.
  - hue:        Animates hue rotation over time. h=expr with t variable.
                Cycles ±30° over 30s to shift spectrum through gold palette.
  - boxblur:    Applied to cover art background. 20px, 3 passes for smooth blur.
  - eq:         Darken background: brightness=-0.2, saturation=0.6.
  - subtitles:  libass renderer. Uses .ass file for colored host prefixes.
  - blend=screen: Makes black areas of CQT spectrogram transparent on overlay.
"""

import sys
import os
import subprocess

FFMPEG   = "/root/.openclaw/utilities/ffmpeg/ffmpeg"
LD_ENV   = {"LD_LIBRARY_PATH": "/root/.openclaw/utilities/ffmpeg", **os.environ}

ASSETS_DIR   = "/root/.openclaw/workspace/skills/podcast-gen/assets"
COVER_ART    = os.path.join(ASSETS_DIR, "cover.png")

# CQT circle size — 800x800 looks good, centered on 1920x1080
CQT_SIZE = 800
PAD_X    = (1920 - CQT_SIZE) // 2   # 560
PAD_Y    = (1080 - CQT_SIZE) // 2   # 140

# Hue cycle: slow shift ±30° over 30s to warm up/cool down the spectrum colors
HUE_EXPR = "30*sin(2*3.14159265*t/30)"


def build_filter_complex(captions_ass):
    """
    Build the ffmpeg -filter_complex string.

    Input streams:
      [0:v] = cover art (looped still image)
      [1:a] = podcast audio

    Output:
      [vout] = composited video with waveform + subtitles
    """
    # Escape colon in path for ffmpeg filter syntax
    ass_escaped = captions_ass.replace("\\", "/").replace(":", "\\:")

    fc = (
        # ── Background: blur and dim cover art ──────────────────────────
        f"[0:v]scale=1920:1080,"
        f"boxblur=luma_radius=20:luma_power=3,"
        f"eq=brightness=-0.20:saturation=0.6"
        f"[bg];"

        # ── CQT spectrum, 800x800 ────────────────────────────────────────
        # showcqt: constant-Q transform spectrogram
        # count=1: mono sum, csp=bt709: proper color space
        # basefreq/endfreq: focus on speech + music range
        f"[1:a]showcqt=s={CQT_SIZE}x{CQT_SIZE}:count=1:csp=bt709:"
        f"basefreq=20:endfreq=14000:gamma=3"
        f"[cqt];"

        # ── Hue-cycle the spectrum (slow warm color shift) ───────────────
        f"[cqt]hue=h={HUE_EXPR}:s=1.3"
        f"[cqt_h];"

        # ── Circular crop via geq (YUV planes) ──────────────────────────
        # Outside circle: lum=0, cb=128 (neutral chroma), cr=128
        f"[cqt_h]geq="
        f"lum='if(lte(hypot(X-W/2\\,Y-H/2)\\,{CQT_SIZE//2 - 4})\\,lum(X\\,Y)\\,0)':"
        f"cb='if(lte(hypot(X-W/2\\,Y-H/2)\\,{CQT_SIZE//2 - 4})\\,cb(X\\,Y)\\,128)':"
        f"cr='if(lte(hypot(X-W/2\\,Y-H/2)\\,{CQT_SIZE//2 - 4})\\,cr(X\\,Y)\\,128)'"
        f"[circ];"

        # ── Pad to 1920x1080 (center), then screen-blend onto bg ────────
        # Screen blend: result = 1-(1-a)(1-b), black in cqt = transparent
        f"[circ]pad=1920:1080:{PAD_X}:{PAD_Y}:color=black"
        f"[padded];"

        f"[bg][padded]blend=all_mode=screen:all_opacity=0.90"
        f"[blended];"

        # ── Burn in ASS subtitles ────────────────────────────────────────
        f"[blended]subtitles={ass_escaped}"
        f"[vout]"
    )
    return fc


def main():
    if len(sys.argv) < 2:
        print("Usage: gen_video.py <episode_dir> [output_mp4]")
        sys.exit(1)

    episode_dir = sys.argv[1].rstrip("/")
    audio_path  = os.path.join(episode_dir, "podcast.mp3")
    captions    = os.path.join(episode_dir, "captions.ass")

    # Determine output path
    if len(sys.argv) >= 3:
        output_mp4 = sys.argv[2]
    else:
        ep_name    = os.path.basename(episode_dir)
        output_mp4 = os.path.join(episode_dir, f"{ep_name}.mp4")

    # Sanity checks
    for path, label in [(COVER_ART, "Cover art"), (audio_path, "Audio"),
                        (captions, "Captions ASS")]:
        if not os.path.exists(path):
            print(f"ERROR: {label} not found: {path}")
            sys.exit(1)

    print(f"Episode dir : {episode_dir}")
    print(f"Cover art   : {COVER_ART}")
    print(f"Audio       : {audio_path}")
    print(f"Captions    : {captions}")
    print(f"Output      : {output_mp4}")
    print()

    fc = build_filter_complex(captions)

    cmd = [
        FFMPEG,
        "-y",                          # overwrite output
        "-loop", "1",
        "-i", COVER_ART,               # [0:v] still image
        "-i", audio_path,              # [1:a] podcast audio
        "-filter_complex", fc,
        "-map", "[vout]",
        "-map", "1:a",
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "20",                  # quality — lower = better (18-28 range)
        "-pix_fmt", "yuv420p",
        "-c:a", "aac",
        "-b:a", "192k",
        "-shortest",                   # stop at end of audio
        "-movflags", "+faststart",     # YouTube streaming optimization
        output_mp4,
    ]

    print("Running ffmpeg command:")
    print(" \\\n  ".join(cmd))
    print()
    print("Rendering... (this will take several minutes for a full episode)")
    print("Progress is shown below:")
    print("-" * 60)

    # Run with output streaming to terminal
    result = subprocess.run(cmd, env=LD_ENV)

    if result.returncode == 0:
        size_mb = os.path.getsize(output_mp4) / (1024 * 1024)
        print(f"\n✓ Video rendered successfully!")
        print(f"  Output : {output_mp4}")
        print(f"  Size   : {size_mb:.1f} MB")
    else:
        print(f"\n✗ ffmpeg exited with code {result.returncode}")
        sys.exit(result.returncode)


if __name__ == "__main__":
    main()
